import type { GanttTask, GanttEmployee } from "../types";

// The sample plan below is authored around this anchor date (the original "today").
// At module load we shift every task date by the gap between the anchor and the real
// current day, so the demo always lands on today — the today marker keeps sitting just
// after the Research phase, exactly like the design, and never goes stale.
const DESIGN_ANCHOR = "2026-08-09";
const DAY_MS = 24 * 60 * 60 * 1000;

function ymdToUtcMs(ymd: string): number {
  const [y, m, d] = ymd.split("-").map(Number);
  return Date.UTC(y, m - 1, d);
}

const now = new Date();
const shiftDays = Math.round(
  (Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()) - ymdToUtcMs(DESIGN_ANCHOR)) / DAY_MS
);

function shiftDate(ymd: string): string {
  const [y, m, d] = ymd.split("-").map(Number);
  const t = new Date(Date.UTC(y, m - 1, d + shiftDays));
  const mm = String(t.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(t.getUTCDate()).padStart(2, "0");
  return `${t.getUTCFullYear()}-${mm}-${dd}`;
}

function phaseIdFromColor(color: GanttTask["phaseColor"]): GanttTask["phaseId"] {
  if (color === "green") return "research";
  if (color === "pink") return "design";
  if (color === "blue") return "development";
  if (color === "orange") return "release";
  if (color === "gray") return "analysis";
  return "general";
}

export const ganttEmployees: GanttEmployee[] = [
  { id: "emp-pm-01", name: "Rina Putri", nickname: "RP", role: "Product Manager" },
  { id: "emp-ui-01", name: "Aditya Pratama", nickname: "AD", role: "UI/UX Designer" },
  { id: "emp-fe-01", name: "Kevin Saputra", nickname: "KS", role: "Frontend Developer" },
  { id: "emp-be-01", name: "Nabila Sari", nickname: "NS", role: "Backend Developer" },
  { id: "emp-qa-01", name: "Hendra Wijaya", nickname: "HW", role: "QA Engineer" },
  { id: "emp-ba-01", name: "Salsa Maharani", nickname: "SM", role: "Business Analyst" },
];

const rawTasks: GanttTask[] = [
  {
    id: 1,
    parentId: null,
    code: "",
    name: "Product launch",
    owner: "PMO",
    status: "on-track",
    progress: 56,
    kind: "summary",
    start: "2026-07-22",
    end: "2026-11-21",
    resources: [{ role: "Lead", tone: "indigo" }],
    phaseColor: "gray",
  },
  {
    id: 2,
    parentId: 1,
    code: "",
    name: "Kickoff",
    owner: "PM",
    status: "done",
    progress: 100,
    kind: "milestone",
    start: "2026-07-22",
    end: "2026-07-22",
    resources: [{ role: "PM", tone: "slate" }],
    phaseColor: "green",
  },
  {
    id: 3,
    parentId: 1,
    code: "",
    name: "Closure",
    owner: "PMO",
    status: "on-track",
    progress: 0,
    kind: "task",
    start: "2026-08-01",
    end: "2026-08-05",
    resources: [{ role: "PMO", tone: "slate" }],
    phaseColor: "gray",
  },
  {
    id: 4,
    parentId: null,
    code: "",
    name: "Research",
    owner: "Research Lead",
    status: "done",
    progress: 100,
    kind: "summary",
    start: "2026-07-22",
    end: "2026-08-22",
    resources: [{ role: "Lead", tone: "teal" }],
    phaseColor: "green",
  },
  {
    id: 5,
    parentId: 4,
    code: "",
    name: "Project definition and research",
    owner: "Analyst",
    status: "done",
    progress: 100,
    kind: "task",
    start: "2026-07-22",
    end: "2026-07-30",
    resources: [{ role: "Analyst", tone: "teal" }],
    phaseColor: "green",
  },
  {
    id: 6,
    parentId: 4,
    code: "",
    name: "Conceptualizing",
    owner: "Designer",
    status: "done",
    progress: 100,
    kind: "task",
    start: "2026-07-31",
    end: "2026-08-04",
    resources: [{ role: "Designer", tone: "rose" }],
    phaseColor: "green",
    dependencies: [5],
  },
  {
    id: 7,
    parentId: 4,
    code: "",
    name: "Define goals and purpose",
    owner: "PM",
    status: "done",
    progress: 100,
    kind: "task",
    start: "2026-08-05",
    end: "2026-08-08",
    resources: [{ role: "PM", tone: "indigo" }],
    phaseColor: "green",
    dependencies: [6],
  },
  {
    id: 8,
    parentId: 4,
    code: "",
    name: "Budget definition",
    owner: "Finance",
    status: "done",
    progress: 100,
    kind: "task",
    start: "2026-08-09",
    end: "2026-08-13",
    resources: [{ role: "Finance", tone: "amber" }],
    phaseColor: "green",
    dependencies: [7],
  },
  {
    id: 9,
    parentId: 4,
    code: "",
    name: "Revision",
    owner: "Reviewer",
    status: "done",
    progress: 100,
    kind: "task",
    start: "2026-08-14",
    end: "2026-08-18",
    resources: [{ role: "Reviewer", tone: "amber" }],
    phaseColor: "green",
    dependencies: [8],
  },
  {
    id: 10,
    parentId: 4,
    code: "",
    name: "Resource mapping",
    owner: "PMO",
    status: "done",
    progress: 100,
    kind: "task",
    start: "2026-08-19",
    end: "2026-08-22",
    resources: [{ role: "PMO", tone: "slate" }],
    phaseColor: "green",
    dependencies: [9],
  },
  {
    id: 11,
    parentId: null,
    code: "",
    name: "Analysis",
    owner: "Analyst Lead",
    status: "on-track",
    progress: 60,
    kind: "summary",
    start: "2026-08-23",
    end: "2026-09-05",
    resources: [{ role: "Lead", tone: "teal" }],
    phaseColor: "gray",
    dependencies: [4],
  },
  {
    id: 12,
    parentId: 11,
    code: "",
    name: "Meetings with Stakeholders",
    owner: "PM",
    status: "done",
    progress: 100,
    kind: "task",
    start: "2026-08-23",
    end: "2026-08-27",
    resources: [{ role: "PM", tone: "slate" }],
    phaseColor: "green",
  },
  {
    id: 13,
    parentId: 11,
    code: "",
    name: "Document findings",
    owner: "Analyst",
    status: "on-track",
    progress: 70,
    kind: "task",
    start: "2026-08-28",
    end: "2026-09-03",
    resources: [{ role: "Analyst", tone: "teal" }],
    phaseColor: "green",
    dependencies: [12],
  },
  {
    id: 14,
    parentId: 11,
    code: "",
    name: "Analysis complete",
    owner: "PM",
    status: "on-track",
    progress: 0,
    kind: "milestone",
    start: "2026-09-05",
    end: "2026-09-05",
    resources: [{ role: "PM", tone: "indigo" }],
    phaseColor: "green",
    dependencies: [13],
  },
  {
    id: 15,
    parentId: null,
    code: "",
    name: "Documentation",
    owner: "Doc Lead",
    status: "on-track",
    progress: 40,
    kind: "summary",
    start: "2026-09-06",
    end: "2026-09-25",
    resources: [{ role: "Lead", tone: "indigo" }],
    phaseColor: "gray",
    dependencies: [11],
  },
  {
    id: 16,
    parentId: 15,
    code: "",
    name: "Research competitors",
    owner: "Analyst",
    status: "on-track",
    progress: 50,
    kind: "task",
    start: "2026-09-06",
    end: "2026-09-11",
    resources: [{ role: "Analyst", tone: "teal" }],
    phaseColor: "pink",
  },
  {
    id: 17,
    parentId: 15,
    code: "",
    name: "Define requirements and expectations",
    owner: "BA",
    status: "on-track",
    progress: 30,
    kind: "task",
    start: "2026-09-12",
    end: "2026-09-17",
    resources: [{ role: "BA", tone: "rose" }],
    phaseColor: "pink",
    dependencies: [16],
  },
  {
    id: 18,
    parentId: 15,
    code: "",
    name: "Features",
    owner: "Product",
    status: "on-track",
    progress: 20,
    kind: "task",
    start: "2026-09-18",
    end: "2026-09-22",
    resources: [{ role: "Product", tone: "teal" }],
    phaseColor: "pink",
    dependencies: [17],
  },
  {
    id: 19,
    parentId: 15,
    code: "",
    name: "Functionalities",
    owner: "Architect",
    status: "on-track",
    progress: 0,
    kind: "task",
    start: "2026-09-23",
    end: "2026-09-25",
    resources: [{ role: "Architect", tone: "indigo" }],
    phaseColor: "pink",
    dependencies: [18],
  },
  {
    id: 20,
    parentId: null,
    code: "",
    name: "Design",
    owner: "Design Lead",
    status: "at-risk",
    progress: 25,
    kind: "summary",
    start: "2026-09-26",
    end: "2026-10-17",
    resources: [{ role: "Lead", tone: "rose" }],
    phaseColor: "pink",
    dependencies: [15],
  },
  {
    id: 21,
    parentId: 20,
    code: "",
    name: "Page design",
    owner: "Designer",
    status: "on-track",
    progress: 40,
    kind: "task",
    start: "2026-09-26",
    end: "2026-10-02",
    resources: [{ role: "Designer", tone: "rose" }],
    phaseColor: "pink",
  },
  {
    id: 22,
    parentId: 20,
    code: "",
    name: "Database design",
    owner: "DBA",
    status: "on-track",
    progress: 30,
    kind: "task",
    start: "2026-10-03",
    end: "2026-10-08",
    resources: [{ role: "DBA", tone: "indigo" }],
    phaseColor: "pink",
    dependencies: [21],
  },
  {
    id: 23,
    parentId: 20,
    code: "",
    name: "Review",
    owner: "Reviewer",
    status: "at-risk",
    progress: 10,
    kind: "task",
    start: "2026-10-09",
    end: "2026-10-14",
    resources: [{ role: "Reviewer", tone: "amber" }],
    phaseColor: "pink",
    dependencies: [22],
  },
  {
    id: 24,
    parentId: 20,
    code: "",
    name: "Approval",
    owner: "Stakeholder",
    status: "on-track",
    progress: 0,
    kind: "milestone",
    start: "2026-10-17",
    end: "2026-10-17",
    resources: [{ role: "Stakeholder", tone: "amber" }],
    phaseColor: "orange",
    dependencies: [23],
  },
  {
    id: 25,
    parentId: null,
    code: "",
    name: "Development",
    owner: "Dev Lead",
    status: "on-track",
    progress: 15,
    kind: "summary",
    start: "2026-10-18",
    end: "2026-11-07",
    resources: [{ role: "Lead", tone: "indigo" }],
    phaseColor: "blue",
    dependencies: [20],
  },
  {
    id: 26,
    parentId: 25,
    code: "",
    name: "Code",
    owner: "Developer",
    status: "on-track",
    progress: 20,
    kind: "task",
    start: "2026-10-18",
    end: "2026-10-30",
    resources: [{ role: "Dev", tone: "indigo" }],
    phaseColor: "blue",
  },
  {
    id: 27,
    parentId: 25,
    code: "",
    name: "QA site",
    owner: "QA",
    status: "on-track",
    progress: 0,
    kind: "task",
    start: "2026-10-31",
    end: "2026-11-07",
    resources: [{ role: "QA", tone: "teal" }],
    phaseColor: "blue",
    dependencies: [26],
  },
  {
    id: 28,
    parentId: null,
    code: "",
    name: "Review",
    owner: "Review Lead",
    status: "on-track",
    progress: 0,
    kind: "summary",
    start: "2026-11-08",
    end: "2026-11-21",
    resources: [{ role: "Lead", tone: "amber" }],
    phaseColor: "orange",
    dependencies: [25],
  },
  {
    id: 29,
    parentId: 28,
    code: "",
    name: "Review project",
    owner: "PM",
    status: "on-track",
    progress: 0,
    kind: "task",
    start: "2026-11-08",
    end: "2026-11-14",
    resources: [{ role: "PM", tone: "slate" }],
    phaseColor: "orange",
  },
  {
    id: 30,
    parentId: 28,
    code: "",
    name: "Sign off",
    owner: "Stakeholder",
    status: "on-track",
    progress: 0,
    kind: "milestone",
    start: "2026-11-21",
    end: "2026-11-21",
    resources: [{ role: "Stakeholder", tone: "amber" }],
    phaseColor: "orange",
    dependencies: [29],
  },
];

// Shift the whole plan onto the current date so the demo (and its today marker) stays real-time.
export const ganttTasks: GanttTask[] = rawTasks.map((task) => ({
  ...task,
  start: shiftDate(task.start),
  end: shiftDate(task.end),
  resources: task.resources.map((resource, index) => {
    const employee = ganttEmployees[index % ganttEmployees.length];
    return { ...resource, employeeId: employee.id, allocation: resource.allocation ?? 60, isPic: index === 0 };
  }),
  phaseId: task.phaseId ?? phaseIdFromColor(task.phaseColor),
  dependencies: task.dependencies?.map((predecessorId) => (typeof predecessorId === "number" ? { predecessorId, type: "finish-to-start" as const } : predecessorId)),
  effort: task.kind === "task" ? { value: Math.max(2, Math.round((ymdToUtcMs(task.end) - ymdToUtcMs(task.start)) / DAY_MS) + 1), unit: "person-days" } : undefined,
  weight: task.kind === "task" ? 1 : undefined,
}));
